# Generated by Django 2.1.3 on 2018-11-18 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0002_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pictures',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
