# Generated by Django 2.1.3 on 2018-11-18 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0003_product_pictures'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pictures',
            field=models.ImageField(null=True, upload_to='collection/'),
        ),
    ]
